const fontFamily = {
  font1: "'Gotham', Arial, sans-serif",
  font2: "'Hind Vadodara', Arial, sans-serif",
  font3: "'Manrope', Arial, sans-serif",
  font4: "'Poppins', Arial, sans-serif",
};

const textVariants = {
  /*INTERNAL_DO_NOT_USE: {
    fontFamily: fontFamily.font4,
    fontSize: 12,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.33,
  },
  INTERNAL_DO_NOT_USE: {
    fontFamily: fontFamily.font4,
    fontSize: 10,
    fontWeight: 600,
    textTransform: "initial",
    lineHeight: 1.8,
  },
  INTERNAL_DO_NOT_USE: {
    fontFamily: fontFamily.font4,
    fontSize: 16,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.5,
  },
  INTERNAL_DO_NOT_USE: {
    fontFamily: fontFamily.font4,
    fontSize: 12,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.33,
  },
  INTERNAL_DO_NOT_USE: {
    fontFamily: fontFamily.font4,
    fontSize: 73,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.0,
  },
  INTERNAL_DO_NOT_USE: {
    fontFamily: fontFamily.font4,
    fontSize: 24,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.0,
  },
  INTERNAL_DO_NOT_USE: {
    fontFamily: fontFamily.font4,
    fontSize: 32,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.0,
  },
  INTERNAL_DO_NOT_USE: {
    fontFamily: fontFamily.font4,
    fontSize: 16,
    fontWeight: 600,
    textTransform: "initial",
    lineHeight: 1.5,
  },
  INTERNAL_DO_NOT_USE: {
    fontFamily: fontFamily.font4,
    fontSize: 56,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.0,
  },*/
  "btn50-bs": {
    fontFamily: fontFamily.font1,
    fontSize: 10,
    fontWeight: 500,
    textTransform: "uppercase",
    lineHeight: 1.2,
  },
  "btn100-bs": {
    fontFamily: fontFamily.font3,
    fontSize: 12,
    fontWeight: 600,
    textTransform: "initial",
    lineHeight: 1.67,
  },
  "btn105-bs": {
    fontFamily: fontFamily.font3,
    fontSize: 12,
    fontWeight: 600,
    textTransform: "initial",
    lineHeight: 1.67,
  },
  "btn110-bs": {
    fontFamily: fontFamily.font3,
    fontSize: 12,
    fontWeight: 600,
    textTransform: "uppercase",
    lineHeight: 1.67,
  },
  "btn200-bs": {
    fontFamily: fontFamily.font3,
    fontSize: 14,
    fontWeight: 600,
    textTransform: "initial",
    lineHeight: 1.71,
  },
  "btn205-bs": {
    fontFamily: fontFamily.font3,
    fontSize: 14,
    fontWeight: 600,
    textTransform: "initial",
    lineHeight: 1.71,
  },
  "btn210-bs": {
    fontFamily: fontFamily.font3,
    fontSize: 14,
    fontWeight: 600,
    textTransform: "uppercase",
    lineHeight: 1.71,
  },
  "btn300-bs": {
    fontFamily: fontFamily.font3,
    fontSize: 16,
    fontWeight: 600,
    textTransform: "initial",
    lineHeight: 1.5,
  },
  "btn310-bs": {
    fontFamily: fontFamily.font3,
    fontSize: 16,
    fontWeight: 600,
    textTransform: "uppercase",
    lineHeight: 1.5,
  },
  "h1000-xl": {
    fontFamily: fontFamily.font1,
    fontSize: 120,
    fontWeight: 500,
    textTransform: "initial",
    lineHeight: 1.07,
  },
  "h200-bs": {
    fontFamily: fontFamily.font1,
    fontSize: 16,
    fontWeight: 500,
    textTransform: "initial",
    lineHeight: 1.5,
  },
  "h200-sm": {
    fontFamily: fontFamily.font1,
    fontSize: 18,
    fontWeight: 500,
    textTransform: "initial",
    lineHeight: 1.33,
  },
  "h200-xl": {
    fontFamily: fontFamily.font1,
    fontSize: 20,
    fontWeight: 500,
    textTransform: "initial",
    lineHeight: 1.4,
  },
  "h300-lg": {
    fontFamily: fontFamily.font1,
    fontSize: 20,
    fontWeight: 500,
    textTransform: "initial",
    lineHeight: 1.4,
  },
  "h300-sm": {
    fontFamily: fontFamily.font1,
    fontSize: 16,
    fontWeight: 500,
    textTransform: "initial",
    lineHeight: 1.5,
  },
  "h300-xl": {
    fontFamily: fontFamily.font2,
    fontSize: 24,
    fontWeight: 600,
    textTransform: "initial",
    lineHeight: 1.17,
  },
  "h400-bs": {
    fontFamily: fontFamily.font1,
    fontSize: 20,
    fontWeight: 500,
    textTransform: "initial",
    lineHeight: 1.6,
  },
  "h400-lg": {
    fontFamily: fontFamily.font2,
    fontSize: 28,
    fontWeight: 600,
    textTransform: "initial",
    lineHeight: 1.14,
  },
  "h400-xl": {
    fontFamily: fontFamily.font1,
    fontSize: 32,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.25,
  },
  "h500-bs": {
    fontFamily: fontFamily.font1,
    fontSize: 20,
    fontWeight: 500,
    textTransform: "initial",
    lineHeight: 1.4,
  },
  "h500-lg": {
    fontFamily: fontFamily.font1,
    fontSize: 32,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.25,
  },
  "h500-sm": {
    fontFamily: fontFamily.font1,
    fontSize: 28,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.29,
  },
  "h500-xl": {
    fontFamily: fontFamily.font1,
    fontSize: 40,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.2,
  },
  "h600-bs": {
    fontFamily: fontFamily.font1,
    fontSize: 20,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.4,
  },
  "h600-lg": {
    fontFamily: fontFamily.font1,
    fontSize: 32,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.25,
  },
  "h600-sm": {
    fontFamily: fontFamily.font1,
    fontSize: 24,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.17,
  },
  "h600-xl": {
    fontFamily: fontFamily.font1,
    fontSize: 48,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.17,
  },
  "h800-bs": {
    fontFamily: fontFamily.font1,
    fontSize: 26,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.38,
  },
  "h800-lg": {
    fontFamily: fontFamily.font1,
    fontSize: 48,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.17,
  },
  "h800-sm": {
    fontFamily: fontFamily.font1,
    fontSize: 40,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.2,
  },
  "h800-xl": {
    fontFamily: fontFamily.font1,
    fontSize: 64,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.13,
  },
  "h900-lg": {
    fontFamily: fontFamily.font1,
    fontSize: 64,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.13,
  },
  "h900-sm": {
    fontFamily: fontFamily.font1,
    fontSize: 48,
    fontWeight: 700,
    textTransform: "initial",
    lineHeight: 1.17,
  },
  "h900-xl": {
    fontFamily: fontFamily.font2,
    fontSize: 88,
    fontWeight: 600,
    textTransform: "initial",
    lineHeight: 1.12,
  },
  "input-error100-bs": {
    fontFamily: fontFamily.font3,
    fontSize: 13,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.2,
  },
  "input-label200-bs": {
    fontFamily: fontFamily.font3,
    fontSize: 14,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.43,
  },
  "input-label300-bs": {
    fontFamily: fontFamily.font3,
    fontSize: 16,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.5,
  },
  "input-val100-bs": {
    fontFamily: fontFamily.font3,
    fontSize: 14,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.12,
  },
  "input-val200-bs": {
    fontFamily: fontFamily.font3,
    fontSize: 16,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.48,
  },
  "p400-lg": {
    fontFamily: fontFamily.font3,
    fontSize: 12,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.67,
  },
  "p400-xl": {
    fontFamily: fontFamily.font3,
    fontSize: 14,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.71,
  },
  "p500-lg": {
    fontFamily: fontFamily.font3,
    fontSize: 14,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.71,
  },
  "p500-xl": {
    fontFamily: fontFamily.font3,
    fontSize: 16,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.75,
  },
  "p600-bs": {
    fontFamily: fontFamily.font3,
    fontSize: 12,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.67,
  },
  "p600-lg": {
    fontFamily: fontFamily.font3,
    fontSize: 16,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.75,
  },
  "p600-sm": {
    fontFamily: fontFamily.font3,
    fontSize: 14,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.71,
  },
  "p600-xl": {
    fontFamily: fontFamily.font3,
    fontSize: 18,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.78,
  },
  "p700-lg": {
    fontFamily: fontFamily.font3,
    fontSize: 16,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.75,
  },
  "p700-sm": {
    fontFamily: fontFamily.font3,
    fontSize: 14,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.71,
  },
  "p700-xl": {
    fontFamily: fontFamily.font3,
    fontSize: 20,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.8,
  },
  "p800-lg": {
    fontFamily: fontFamily.font3,
    fontSize: 20,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.4,
  },
  "p800-sm": {
    fontFamily: fontFamily.font3,
    fontSize: 16,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.5,
  },
  "p800-xl": {
    fontFamily: fontFamily.font3,
    fontSize: 24,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.33,
  },
  "p900-bs": {
    fontFamily: fontFamily.font2,
    fontSize: 32,
    fontWeight: 400,
    textTransform: "initial",
    lineHeight: 1.32,
  },
};

module.exports = { fontFamily, textVariants };
