import { lazy, Suspense, SVGAttributes } from "react";

/* eslint-disable prettier/prettier */

const LazyIconAdvanced = lazy(() => import( /* webpackChunkName: "icons" */ "./advanced.svg"));
const LazyIconArrowDownIOS = lazy(() => import( /* webpackChunkName: "icons" */ "./arrow-down-ios.svg"));
const LazyIconArrowDown = lazy(() => import( /* webpackChunkName: "icons" */ "./arrow-down.svg"));
const LazyIconArrow = lazy(() => import( /* webpackChunkName: "icons" */ "./arrow.svg"));
const LazyIconAuroxLogo = lazy(() => import( /* webpackChunkName: "icons" */ "./aurox_logo.svg"));
const LazyIconAuroxCircle = lazy(() => import( /* webpackChunkName: "icons" */ "./aurox-circle.svg"));
const LazyIconAvalanche = lazy(() => import( /* webpackChunkName: "icons" */ "./avalanche.svg"));
const LazyIconBankAccount = lazy(() => import( /* webpackChunkName: "icons" */ "./bank-account.svg"));
const LazyIconBinance = lazy(() => import( /* webpackChunkName: "icons" */ "./binance.svg"));
const LazyIconBlueTransferBtn = lazy(() => import( /* webpackChunkName: "icons" */ "./blue-transfer-btn.svg"));
const LazyIconCheck = lazy(() => import( /* webpackChunkName: "icons" */ "./check.svg"));
const LazyIconCheckbox = lazy(() => import( /* webpackChunkName: "icons" */ "./checkbox-checked.svg"));
const LazyIconCheckboxBorder = lazy(() => import( /* webpackChunkName: "icons" */ "./checkbox-unchecked.svg"));
const LazyIconChevronRight = lazy(() => import( /* webpackChunkName: "icons" */ "./chevron-right.svg"));
const LazyIconClear = lazy(() => import( /* webpackChunkName: "icons" */ "./clear.svg"));
const LazyIconClose = lazy(() => import( /* webpackChunkName: "icons" */ "./close.svg"));
const LazyIconClose2 = lazy(() => import( /* webpackChunkName: "icons" */ "./close2.svg"));
const LazyIconCoinTossGray = lazy(() => import( /* webpackChunkName: "icons" */ "./coin-toss-gray.svg"));
const LazyIconCoinToss = lazy(() => import( /* webpackChunkName: "icons" */ "./coin-toss.svg"));
const LazyIconDailyCalendarGray = lazy(() => import( /* webpackChunkName: "icons" */ "./daily-calendar-gray.svg"));
const LazyIconDailyCalendar = lazy(() => import( /* webpackChunkName: "icons" */ "./daily-calendar.svg"));
const LazyIconDanger = lazy(() => import( /* webpackChunkName: "icons" */ "./danger.svg"));
const LazyIconDebitCard = lazy(() => import( /* webpackChunkName: "icons" */ "./debit-card.svg"));
const LazyIconDiamond = lazy(() => import( /* webpackChunkName: "icons" */ "./diamond.svg"));
const LazyIconDiscordGray = lazy(() => import( /* webpackChunkName: "icons" */ "./discord-gray.svg"));
const LazyIconDiscordHighestGray = lazy(() => import( /* webpackChunkName: "icons" */ "./discord-highest-gray.svg"));
const LazyIconDiscordHighest = lazy(() => import( /* webpackChunkName: "icons" */ "./discord-highest.svg"));
const LazyIconDiscordLevelTwoGray = lazy(() => import( /* webpackChunkName: "icons" */ "./discord-level-two-gray.svg"));
const LazyIconDiscordLevelTwo = lazy(() => import( /* webpackChunkName: "icons" */ "./discord-level-two.svg"));
const LazyIconDiscord = lazy(() => import( /* webpackChunkName: "icons" */ "./discord.svg"));
const LazyIconEdit = lazy(() => import( /* webpackChunkName: "icons" */ "./edit.svg"));
const LazyIconEthereum = lazy(() => import( /* webpackChunkName: "icons" */ "./ethereum.svg"));
const LazyIconFail = lazy(() => import( /* webpackChunkName: "icons" */ "./fail.svg"));
const LazyIconFantom = lazy(() => import( /* webpackChunkName: "icons" */ "./fantom.svg"));
const LazyIconFilterAlt = lazy(() => import( /* webpackChunkName: "icons" */ "./filter-alt.svg"));
const LazyIconFullScreen = lazy(() => import( /* webpackChunkName: "icons" */ "./full-screen.svg"));
const LazyIconGasStation = lazy(() => import( /* webpackChunkName: "icons" */ "./gas-station.svg"));
const LazyIconGeneral = lazy(() => import( /* webpackChunkName: "icons" */ "./general.svg"));
const LazyIconGiftGray = lazy(() => import( /* webpackChunkName: "icons" */ "./gift-gray.svg"));
const LazyIconGift = lazy(() => import( /* webpackChunkName: "icons" */ "./gift.svg"));
const LazyIconHome = lazy(() => import( /* webpackChunkName: "icons" */ "./home.svg"));
const LazyIconHWLattice = lazy(() => import( /* webpackChunkName: "icons" */ "./hw-lattice.svg"));
const LazyIconHWLedger = lazy(() => import( /* webpackChunkName: "icons" */ "./hw-ledger.svg"));
const LazyIconHWQrBased = lazy(() => import( /* webpackChunkName: "icons" */ "./hw-qr-based.svg"));
const LazyIconHWTrezor = lazy(() => import( /* webpackChunkName: "icons" */ "./hw-trezor.svg"));
const LazyIconInfo = lazy(() => import( /* webpackChunkName: "icons" */ "./info.svg"));
const LazyIconInviteAuroxGray = lazy(() => import( /* webpackChunkName: "icons" */ "./invite-aurox-gray.svg"));
const LazyIconInviteAurox = lazy(() => import( /* webpackChunkName: "icons" */ "./invite-aurox.svg"));
const LazyIconInviteGray = lazy(() => import( /* webpackChunkName: "icons" */ "./invite-gray.svg"));
const LazyIconInvite = lazy(() => import( /* webpackChunkName: "icons" */ "./invite.svg"));
const LazyIconLink = lazy(() => import( /* webpackChunkName: "icons" */ "./link.svg"));
const LazyIconLogo = lazy(() => import( /* webpackChunkName: "icons" */ "./logo.svg"));
const LazyIconLogs = lazy(() => import( /* webpackChunkName: "icons" */ "./logs.svg"));
const LazyIconMarkets = lazy(() => import( /* webpackChunkName: "icons" */ "./market.svg"));
const LazyIconMetaMaskFox = lazy(() => import( /* webpackChunkName: "icons" */ "./metamask-fox.svg"));
const LazyIconMoneyTransfer = lazy(() => import( /* webpackChunkName: "icons" */ "./money-transfer.svg"));
const LazyIconNetworks = lazy(() => import( /* webpackChunkName: "icons" */ "./networks.svg"));
const LazyIconTestnet = lazy(() => import( /* webpackChunkName: "icons" */ "./testnet.svg"));
const LazyIconPlus = lazy(() => import( /* webpackChunkName: "icons" */ "./plus.svg"));
const LazyIconNotFound = lazy(() => import( /* webpackChunkName: "icons" */ "./not-found.svg"));
const LazyIconOk = lazy(() => import( /* webpackChunkName: "icons" */ "./ok.svg"));
const LazyIconOpenLink = lazy(() => import( /* webpackChunkName: "icons" */ "./open-link.svg"));
const LazyIconPassword = lazy(() => import( /* webpackChunkName: "icons" */ "./password.svg"));
const LazyIconPayment = lazy(() => import( /* webpackChunkName: "icons" */ "./payment.svg"));
const LazyIconPeopleGray = lazy(() => import( /* webpackChunkName: "icons" */ "./people-gray.svg"));
const LazyIconPeople = lazy(() => import( /* webpackChunkName: "icons" */ "./people.svg"));
const LazyIconPlaceholderNFT = lazy(() => import( /* webpackChunkName: "icons" */ "./placeholder-nft.svg"));
const LazyIconPolygon = lazy(() => import( /* webpackChunkName: "icons" */ "./polygon.svg"));
const LazyIconRadioOff = lazy(() => import( /* webpackChunkName: "icons" */ "./radio-off.svg"));
const LazyIconRadioOn = lazy(() => import( /* webpackChunkName: "icons" */ "./radio-on.svg"));
const LazyIconReceive = lazy(() => import( /* webpackChunkName: "icons" */ "./receive.svg"));
const LazyIconRecovery = lazy(() => import( /* webpackChunkName: "icons" */ "./recovery.svg"));
const LazyIconRewardsSwap = lazy(() => import( /* webpackChunkName: "icons" */ "./rewards-swap.svg"));
const LazyIconSaleTagGray = lazy(() => import( /* webpackChunkName: "icons" */ "./sale-tag-gray.svg"));
const LazyIconSaleTag = lazy(() => import( /* webpackChunkName: "icons" */ "./sale-tag.svg"));
const LazyIconSearch = lazy(() => import( /* webpackChunkName: "icons" */ "./search.svg"));
const LazyIconSendCoinGray = lazy(() => import( /* webpackChunkName: "icons" */ "./send-coin-gray.svg"));
const LazyIconSendCoin = lazy(() => import( /* webpackChunkName: "icons" */ "./send-coin.svg"));
const LazyIconSendNFTGray = lazy(() => import( /* webpackChunkName: "icons" */ "./send-nft-gray.svg"));
const LazyIconSendNFT = lazy(() => import( /* webpackChunkName: "icons" */ "./send-nft.svg"));
const LazyIconSend = lazy(() => import( /* webpackChunkName: "icons" */ "./send.svg"));
const LazyIconStatusDone = lazy(() => import( /* webpackChunkName: "icons" */ "./status-done.svg"));
const LazyIconStatusError = lazy(() => import( /* webpackChunkName: "icons" */ "./status-error.svg"));
const LazyIconStatusFail = lazy(() => import( /* webpackChunkName: "icons" */ "./status-fail.svg"));
const LazyIconStatusPending = lazy(() => import( /* webpackChunkName: "icons" */ "./status-pending.svg"));
const LazyIconStatusSevereWarning = lazy(() => import( /* webpackChunkName: "icons" */ "./status-severe-warning.svg"));
const LazyIconStatusSuccess = lazy(() => import( /* webpackChunkName: "icons" */ "./status-success.svg"));
const LazyIconStatusWarning = lazy(() => import( /* webpackChunkName: "icons" */ "./status-warning.svg"));
const LazyIconSuccessCheckmark = lazy(() => import( /* webpackChunkName: "icons" */ "./success-checkmark.svg"));
const LazyIconSwapGray = lazy(() => import( /* webpackChunkName: "icons" */ "./swap-gray.svg"));
const LazyIconSwap = lazy(() => import( /* webpackChunkName: "icons" */ "./swap.svg"));
const LazyIconSwitchSide = lazy(() => import( /* webpackChunkName: "icons" */ "./switch-side.svg"));
const LazyIconSwitchValues = lazy(() => import( /* webpackChunkName: "icons" */ "./switch-values.svg"));
const LazyIconTicketsGray = lazy(() => import( /* webpackChunkName: "icons" */ "./tickets-gray.svg"));
const LazyIconTickets = lazy(() => import( /* webpackChunkName: "icons" */ "./tickets.svg"));
const LazyIconTransactions = lazy(() => import( /* webpackChunkName: "icons" */ "./transactions.svg"));
const LazyIconUnion = lazy(() => import( /* webpackChunkName: "icons" */ "./union.svg"));
const LazyIconUniswap = lazy(() => import( /* webpackChunkName: "icons" */ "./uniswap.svg"));
const LazyIconUnplugged = lazy(() => import( /* webpackChunkName: "icons" */ "./unplugged.svg"));
const LazyIconVisibilityOff = lazy(() => import( /* webpackChunkName: "icons" */ "./visibility-off.svg"));
const LazyIconVisibilityOn = lazy(() => import( /* webpackChunkName: "icons" */ "./visibility-on.svg"));
const LazyIconWalletConnected = lazy(() => import( /* webpackChunkName: "icons" */ "./wallet-connected.svg"));
const LazyIconWalletDisconnected = lazy(() => import( /* webpackChunkName: "icons" */ "./wallet-disconnected.svg"));
const LazyIconTrash = lazy(() => import( /* webpackChunkName: "icons" */ "./trash.svg"));
const LazySecurity = lazy(() => import( /* webpackChunkName: "icons" */ "./security.svg"));

export type IconProps = SVGAttributes<SVGElement>;

export const IconAdvanced = (props: IconProps) => <Suspense fallback={null}><LazyIconAdvanced {...props} /></Suspense>
export const IconArrowDownIOS = (props: IconProps) => <Suspense fallback={null}><LazyIconArrowDownIOS {...props} /></Suspense>
export const IconArrowDown = (props: IconProps) => <Suspense fallback={null}><LazyIconArrowDown {...props} /></Suspense>
export const IconArrow = (props: IconProps) => <Suspense fallback={null}><LazyIconArrow {...props} /></Suspense>
export const IconAuroxLogo = (props: IconProps) => <Suspense fallback={null}><LazyIconAuroxLogo {...props} /></Suspense>
export const IconAuroxCircle = (props: IconProps) => <Suspense fallback={null}><LazyIconAuroxCircle {...props} /></Suspense>
export const IconAvalanche = (props: IconProps) => <Suspense fallback={null}><LazyIconAvalanche {...props} /></Suspense>
export const IconBankAccount = (props: IconProps) => <Suspense fallback={null}><LazyIconBankAccount {...props} /></Suspense>
export const IconBinance = (props: IconProps) => <Suspense fallback={null}><LazyIconBinance {...props} /></Suspense>
export const IconBlueTransferBtn = (props: IconProps) => <Suspense fallback={null}><LazyIconBlueTransferBtn {...props} /></Suspense>
export const IconCheck = (props: IconProps) => <Suspense fallback={null}><LazyIconCheck {...props} /></Suspense>
export const IconCheckbox = (props: IconProps) => <Suspense fallback={null}><LazyIconCheckbox {...props} /></Suspense>
export const IconCheckboxBorder = (props: IconProps) => <Suspense fallback={null}><LazyIconCheckboxBorder {...props} /></Suspense>
export const IconChevronRight = (props: IconProps) => <Suspense fallback={null}><LazyIconChevronRight {...props} /></Suspense>
export const IconClear = (props: IconProps) => <Suspense fallback={null}><LazyIconClear {...props} /></Suspense>
export const IconClose = (props: IconProps) => <Suspense fallback={null}><LazyIconClose {...props} /></Suspense>
export const IconClose2 = (props: IconProps) => <Suspense fallback={null}><LazyIconClose2 {...props} /></Suspense>
export const IconCoinTossGray = (props: IconProps) => <Suspense fallback={null}><LazyIconCoinTossGray {...props} /></Suspense>
export const IconCoinToss = (props: IconProps) => <Suspense fallback={null}><LazyIconCoinToss {...props} /></Suspense>
export const IconDailyCalendarGray = (props: IconProps) => <Suspense fallback={null}><LazyIconDailyCalendarGray {...props} /></Suspense>
export const IconDailyCalendar = (props: IconProps) => <Suspense fallback={null}><LazyIconDailyCalendar {...props} /></Suspense>
export const IconDanger = (props: IconProps) => <Suspense fallback={null}><LazyIconDanger {...props} /></Suspense>
export const IconDebitCard = (props: IconProps) => <Suspense fallback={null}><LazyIconDebitCard {...props} /></Suspense>
export const IconEdit = (props: IconProps) => <Suspense fallback={null}><LazyIconEdit {...props} /></Suspense>
export const IconDiamond = (props: IconProps) => <Suspense fallback={null}><LazyIconDiamond {...props} /></Suspense>
export const IconDiscordGray = (props: IconProps) => <Suspense fallback={null}><LazyIconDiscordGray {...props} /></Suspense>
export const IconDiscordHighestGray = (props: IconProps) => <Suspense fallback={null}><LazyIconDiscordHighestGray {...props} /></Suspense>
export const IconDiscordHighest = (props: IconProps) => <Suspense fallback={null}><LazyIconDiscordHighest {...props} /></Suspense>
export const IconDiscordLevelTwoGray = (props: IconProps) => <Suspense fallback={null}><LazyIconDiscordLevelTwoGray {...props} /></Suspense>
export const IconDiscordLevelTwo = (props: IconProps) => <Suspense fallback={null}><LazyIconDiscordLevelTwo {...props} /></Suspense>
export const IconDiscord = (props: IconProps) => <Suspense fallback={null}><LazyIconDiscord {...props} /></Suspense>
export const IconEthereum = (props: IconProps) => <Suspense fallback={null}><LazyIconEthereum {...props} /></Suspense>
export const IconFail = (props: IconProps) => <Suspense fallback={null}><LazyIconFail {...props} /></Suspense>
export const IconFantom = (props: IconProps) => <Suspense fallback={null}><LazyIconFantom {...props} /></Suspense>
export const IconFilterAlt = (props: IconProps) => <Suspense fallback={null}><LazyIconFilterAlt {...props} /></Suspense>
export const IconFullScreen = (props: IconProps) => <Suspense fallback={null}><LazyIconFullScreen {...props} /></Suspense>
export const IconGasStation = (props: IconProps) => <Suspense fallback={null}><LazyIconGasStation {...props} /></Suspense>
export const IconGeneral = (props: IconProps) => <Suspense fallback={null}><LazyIconGeneral {...props} /></Suspense>
export const IconGiftGray = (props: IconProps) => <Suspense fallback={null}><LazyIconGiftGray {...props} /></Suspense>
export const IconGift = (props: IconProps) => <Suspense fallback={null}><LazyIconGift {...props} /></Suspense>
export const IconHome = (props: IconProps) => <Suspense fallback={null}><LazyIconHome {...props} /></Suspense>
export const IconHWLattice = (props: IconProps) => <Suspense fallback={null}><LazyIconHWLattice {...props} /></Suspense>
export const IconHWLedger = (props: IconProps) => <Suspense fallback={null}><LazyIconHWLedger {...props} /></Suspense>
export const IconHWQrBased = (props: IconProps) => <Suspense fallback={null}><LazyIconHWQrBased {...props} /></Suspense>
export const IconHWTrezor = (props: IconProps) => <Suspense fallback={null}><LazyIconHWTrezor {...props} /></Suspense>
export const IconInfo = (props: IconProps) => <Suspense fallback={null}><LazyIconInfo {...props} /></Suspense>
export const IconInviteAuroxGray = (props: IconProps) => <Suspense fallback={null}><LazyIconInviteAuroxGray {...props} /></Suspense>
export const IconInviteAurox = (props: IconProps) => <Suspense fallback={null}><LazyIconInviteAurox {...props} /></Suspense>
export const IconInviteGray = (props: IconProps) => <Suspense fallback={null}><LazyIconInviteGray {...props} /></Suspense>
export const IconInvite = (props: IconProps) => <Suspense fallback={null}><LazyIconInvite {...props} /></Suspense>
export const IconLink = (props: IconProps) => <Suspense fallback={null}><LazyIconLink {...props} /></Suspense>
export const IconLogo = (props: IconProps) => <Suspense fallback={null}><LazyIconLogo {...props} /></Suspense>
export const IconLogs = (props: IconProps) => <Suspense fallback={null}><LazyIconLogs {...props} /></Suspense>
export const IconMarkets = (props: IconProps) => <Suspense fallback={null}><LazyIconMarkets {...props} /></Suspense>
export const IconMetaMaskFox = (props: IconProps) => <Suspense fallback={null}><LazyIconMetaMaskFox {...props} /></Suspense>
export const IconMoneyTransfer = (props: IconProps) => <Suspense fallback={null}><LazyIconMoneyTransfer {...props} /></Suspense>
export const IconNetworks = (props: IconProps) => <Suspense fallback={null}><LazyIconNetworks {...props} /></Suspense>
export const IconTestnet = (props: IconProps) => <Suspense fallback={null}><LazyIconTestnet {...props} /></Suspense>
export const IconPlus = (props: IconProps) => <Suspense fallback={null}><LazyIconPlus {...props} /></Suspense>
export const IconNotFound = (props: IconProps) => <Suspense fallback={null}><LazyIconNotFound {...props} /></Suspense>
export const IconOk = (props: IconProps) => <Suspense fallback={null}><LazyIconOk {...props} /></Suspense>
export const IconOpenLink = (props: IconProps) => <Suspense fallback={null}><LazyIconOpenLink {...props} /></Suspense>
export const IconPassword = (props: IconProps) => <Suspense fallback={null}><LazyIconPassword {...props} /></Suspense>
export const IconPayment = (props: IconProps) => <Suspense fallback={null}><LazyIconPayment {...props} /></Suspense>
export const IconPeopleGray = (props: IconProps) => <Suspense fallback={null}><LazyIconPeopleGray {...props} /></Suspense>
export const IconPeople = (props: IconProps) => <Suspense fallback={null}><LazyIconPeople {...props} /></Suspense>
export const IconPlaceholderNFT = (props: IconProps) => <Suspense fallback={null}><LazyIconPlaceholderNFT {...props} /></Suspense>
export const IconPolygon = (props: IconProps) => <Suspense fallback={null}><LazyIconPolygon {...props} /></Suspense>
export const IconRadioOff = (props: IconProps) => <Suspense fallback={null}><LazyIconRadioOff {...props} /></Suspense>
export const IconRadioOn = (props: IconProps) => <Suspense fallback={null}><LazyIconRadioOn {...props} /></Suspense>
export const IconReceive = (props: IconProps) => <Suspense fallback={null}><LazyIconReceive {...props} /></Suspense>
export const IconRecovery = (props: IconProps) => <Suspense fallback={null}><LazyIconRecovery {...props} /></Suspense>
export const IconRewardsSwap = (props: IconProps) => <Suspense fallback={null}><LazyIconRewardsSwap {...props} /></Suspense>
export const IconSaleTagGray = (props: IconProps) => <Suspense fallback={null}><LazyIconSaleTagGray {...props} /></Suspense>
export const IconSaleTag = (props: IconProps) => <Suspense fallback={null}><LazyIconSaleTag {...props} /></Suspense>
export const IconSearch = (props: IconProps) => <Suspense fallback={null}><LazyIconSearch {...props} /></Suspense>
export const IconSendCoinGray = (props: IconProps) => <Suspense fallback={null}><LazyIconSendCoinGray {...props} /></Suspense>
export const IconSendCoin = (props: IconProps) => <Suspense fallback={null}><LazyIconSendCoin {...props} /></Suspense>
export const IconSendNFTGray = (props: IconProps) => <Suspense fallback={null}><LazyIconSendNFTGray {...props} /></Suspense>
export const IconSendNFT = (props: IconProps) => <Suspense fallback={null}><LazyIconSendNFT {...props} /></Suspense>
export const IconSend = (props: IconProps) => <Suspense fallback={null}><LazyIconSend {...props} /></Suspense>
export const IconStatusDone = (props: IconProps) => <Suspense fallback={null}><LazyIconStatusDone {...props} /></Suspense>
export const IconStatusError = (props: IconProps) => <Suspense fallback={null}><LazyIconStatusError {...props} /></Suspense>
export const IconStatusFail = (props: IconProps) => <Suspense fallback={null}><LazyIconStatusFail {...props} /></Suspense>
export const IconStatusPending = (props: IconProps) => <Suspense fallback={null}><LazyIconStatusPending {...props} /></Suspense>
export const IconStatusSevereWarning = (props: IconProps) => <Suspense fallback={null}><LazyIconStatusSevereWarning {...props} /></Suspense>
export const IconStatusSuccess = (props: IconProps) => <Suspense fallback={null}><LazyIconStatusSuccess {...props} /></Suspense>
export const IconStatusWarning = (props: IconProps) => <Suspense fallback={null}><LazyIconStatusWarning {...props} /></Suspense>
export const IconSuccessCheckmark = (props: IconProps) => <Suspense fallback={null}><LazyIconSuccessCheckmark {...props} /></Suspense>
export const IconSwapGray = (props: IconProps) => <Suspense fallback={null}><LazyIconSwapGray {...props} /></Suspense>
export const IconSwap = (props: IconProps) => <Suspense fallback={null}><LazyIconSwap {...props} /></Suspense>
export const IconSwitchSide = (props: IconProps) => <Suspense fallback={null}><LazyIconSwitchSide {...props} /></Suspense>
export const IconSwitchValues = (props: IconProps) => <Suspense fallback={null}><LazyIconSwitchValues {...props} /></Suspense>
export const IconTicketsGray = (props: IconProps) => <Suspense fallback={null}><LazyIconTicketsGray {...props} /></Suspense>
export const IconTickets = (props: IconProps) => <Suspense fallback={null}><LazyIconTickets {...props} /></Suspense>
export const IconTransactions = (props: IconProps) => <Suspense fallback={null}><LazyIconTransactions {...props} /></Suspense>
export const IconUnion = (props: IconProps) => <Suspense fallback={null}><LazyIconUnion {...props} /></Suspense>
export const IconUniswap = (props: IconProps) => <Suspense fallback={null}><LazyIconUniswap {...props} /></Suspense>
export const IconUnplugged = (props: IconProps) => <Suspense fallback={null}><LazyIconUnplugged {...props} /></Suspense>
export const IconVisibilityOff = (props: IconProps) => <Suspense fallback={null}><LazyIconVisibilityOff {...props} /></Suspense>
export const IconVisibilityOn = (props: IconProps) => <Suspense fallback={null}><LazyIconVisibilityOn {...props} /></Suspense>
export const IconWalletConnected = (props: IconProps) => <Suspense fallback={null}><LazyIconWalletConnected {...props} /></Suspense>
export const IconWalletDisconnected = (props: IconProps) => <Suspense fallback={null}><LazyIconWalletDisconnected {...props} /></Suspense>
export const IconTrash = (props: IconProps) => <Suspense fallback={null}><LazyIconTrash {...props} /></Suspense>
export const IconSecurity = (props: IconProps) => <Suspense fallback={null}><LazySecurity {...props} /></Suspense>
