export const GRAPHQL_LEECHER_X_API_KEY = process.env.GRAPHQL_LEECHER_X_API_KEY!;

export const POCKETUNIVERSE_API_KEY = process.env.POCKETUNIVERSE_API_KEY!;
export const SENTRY_PUBLIC_KEY = process.env.SENTRY_PUBLIC_KEY!;
export const UNS_API_KEY = process.env.UNS_API_KEY!;

export const ETHERSCAN_API_KEY = process.env.ETHERSCAN_API_KEY!;
export const BSCSCAN_API_KEY = process.env.BSCSCAN_API_KEY!;
export const POLYGONSCAN_API_KEY = process.env.POLYGONSCAN_API_KEY!;
export const SNOWTRACE_API_KEY = process.env.SNOWTRACE_API_KEY!;

export const INFURA_ETH_MAINNET_API_KEY = process.env.INFURA_ETH_MAINNET_API_KEY!;

export const ALCHEMY_ETH_MAINNET_API_KEY = process.env.ALCHEMY_ETH_MAINNET_API_KEY!;
export const ALCHEMY_POLYGON_MAINNET_API_KEY = process.env.ALCHEMY_POLYGON_MAINNET_API_KEY!;
export const ALCHEMY_ARBITRUM_MAINNET_API_KEY = process.env.ALCHEMY_ARBIRUM_MAINNET_API_KEY!;
export const ALCHEMY_OPTIMISM_MAINNET_API_KEY = process.env.ALCHEMY_OPTIMISM_MAINNET_API_KEY!;

export const QUIKNODE_BSC_API_KEY = process.env.QUIKNODE_BSC_API_KEY!;
export const QUIKNODE_AVALANCHE_MAINNET_API_KEY = process.env.QUIKNODE_AVALANCHE_MAINNET_API_KEY!;

export const BLOCKNATIVE_API_KEY = process.env.BLOCKNATIVE_API_KEY!;
export const BLOCKNATIVE_SECRET_KEY = process.env.BLOCKNATIVE_SECRET_KEY!;
