export type ButtonsToTrack =
  | "Show Hidden Wallets"
  | "Manage Wallets"
  | "Hide Wallet"
  | "Unhide Wallet"
  | "Create Wallet"
  | "Create New Wallet"
  | "Import Wallet"
  | "Import Hardware Wallet"
  | "Market Favorites"
  | "Market Token Favorite"
  | "My Balances Token"
  | "Market Token"
  | "My Balances Search"
  | "My Balances Manage"
  | "Manage Token Filter"
  | "Main Send"
  | "Coin Send"
  | "Main Swap"
  | "Coin Swap"
  | "Hide Wallet Balances"
  | "Enable Notifications"
  | "Disable Notifications"
  | "View Referral Link"
  | "Copy Referral Link"
  | "Imported Token"
  | "Imported NFT"
  | "View Address Explorer URL"
  | "Sent Token"
  | "Sent NFT"
  | "Gasless Swap"
  | "Regular Swap"
  | "Connected with Aurox"
  | "Connected with Metamask"
  | "Simulate"
  | "Not simulated"
  | "Submitted Transaction"
  | "Rejected Transaction";

export type PagesToTrack = "Home" | "Markets" | "Transactions" | "Settings" | "Swap";
